[package]
name = "bevy_serde_lens_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.68", feature = ["full"] }
quote = "1.0.36"
proc-macro2 = "1.0.86"
proc-macro-error = "1.0.4"
